### PR TITLE
Add framework for GitHub actions

### PR DESCRIPTION
**Pull request by datawookie**

### CODE REVIEW

**Comment by daattali** [comment]
This PR contains a lot of commits and code that are unrelated to the GitHub actions framework.

**Comment by datawookie** [comment]
@daattali I cleaned the commit history.

**Comment by daattali** [comment]
Is there a reason this is using very old github actions? I know that the old one results in errors on ubuntu often

**Comment by datawookie** [comment]
@daattali all actions have been updated to latest versions.

**Review by daattali — APPROVED** [review]
The action template was from over a year ago, I've modified the action template to use the current one (from https://github.com/r-lib/actions/tree/v2/examples) 

will merge in morning

**Pull request merged**
